# -*- coding: utf-8 -*-
"""Unigram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZhUJkqr74xh8pHi--iKwXZ2onjgzBsLz
"""

from nltk import ngrams

from nltk.util import ngrams

n=1
text=("I am Dipali Chandre.I am form velapur .currently I am pursuing B.Tech in stream of Information Technology and I had completed my deploma in computer engineering form GPI")
unigram=ngrams(text.split(),n)
for item in unigram:
  print(item)

n=2
text=("I am Dipali Chandre.I am form velapur .currently I am pursuing B.Tech in stream of Information Technology and I had completed my deploma in computer engineering form GPI")
unigram=ngrams(text.split(),n)
for item in unigram:
  print(item)

n=3
text=("I am Dipali Chandre I am form velapur currently I am pursuing B.Tech in stream of Information Technology and I had completed my deploma in computer engineering form GPI")
unigram=ngrams(text.split(),n)
for item in unigram:
  print(item)

n=4
text=("I am Dipali Chandre I am form velapur currently I am pursuing B.Tech in stream of Information Technology and I had completed my deploma in computer engineering form GPI")
unigram=ngrams(text.split(),n)
for item in unigram:
  print(item)